Repository agflow/agstring, pull requests merged in 2019-04, with the labels that each got.

#52 feat: add ContainsSlice()
  contains.go
  contains_test.go
Labels: size/M

#53 refactor: common code / change logic of ContainsSlice to run on probe
  contains.go
  contains_test.go
  string.go
  string_test.go
Labels: size/M

#54 feat: add IsEqual for slices
  contains.go
  string.go
  string_test.go
Labels: size/M

#55 feat: add ReplaceZeroWidthChars function
  replace.go
  replace_test.go
  string.go
  string_test.go
Labels: size/L

#56 feat: update Normalize(), added TrimAndRemoveZeroWidthChars()
  normalize.go
  normalize_test.go
  string.go
  string_test.go
  trim.go
  trim_test.go
Labels: size/L

#57 feat: add reprintf
  string.go
  string_test.go
Labels: size/S

#58 feat: add omit helper
  string.go
  string_test.go
Labels: size/M
