Repository agflow/agstring, pull requests merged in 2019-05, with the labels that each got.

#59 feat(agstring): add mustequal func
  string.go
  string_test.go
Labels: size/XS

#60 refactor: extract equal to its own file
  equal.go
  equal_test.go
  string.go
  string_test.go
Labels: size/L

#61 chore(vendor): bump deps
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/mozillazg/go-unidecode/.travis.yml
  vendor/github.com/mozillazg/go-unidecode/CHANGELOG.md
  vendor/github.com/mozillazg/go-unidecode/Makefile
  vendor/github.com/mozillazg/go-unidecode/README.md
  vendor/github.com/mozillazg/go-unidecode/doc.go
  vendor/github.com/mozillazg/go-unidecode/go.mod
  vendor/github.com/mozillazg/go-unidecode/unidecode.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/github.com/thoas/go-funk/.gitignore
  vendor/github.com/thoas/go-funk/helpers.go
  vendor/github.com/thoas/go-funk/operation.go
  vendor/github.com/thoas/go-funk/presence.go
Labels: size/XS

#63 feat: check if combined strings contains searched strings
  contains.go
  contains_test.go
Labels: size/M

#64 chore: rm iterator interface
  string.go
Labels: size/XS

#65 feat: replace a string only if it is a word
  replace.go
  replace_test.go
Labels: size/S

#66 refactor: rename for common naming
  replace.go
  replace_test.go
Labels: size/S

#67 feat: add tail and noLast
  slice.go
  slice_test.go
  string.go
  string_test.go
Labels: size/L

#68 fix: change head comment in go documentation
  slice.go
Labels: size/XS
